// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ProjetoLoja.Data;

namespace ProjetoLoja.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20190401022605_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.SerialColumn)
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            modelBuilder.Entity("ProjetoLoja.Models.Produto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CategoriaProduto")
                        .IsRequired();

                    b.Property<string>("DescricaoProduto")
                        .IsRequired();

                    b.Property<string>("NomeProduto")
                        .IsRequired();

                    b.Property<double>("PrecoProduto");

                    b.HasKey("Id");

                    b.ToTable("Produtos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoriaProduto = "Infantil",
                            DescricaoProduto = "Boneca",
                            NomeProduto = "Barbie",
                            PrecoProduto = 19.98
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
